<?php

namespace App\Services;

class ToolData
{
    /**
     * Get all tools from Database (Cached)
     */
    public static function getTools()
    {
        return \Illuminate\Support\Facades\Cache::remember('tools_all', 3600, function () {
            $tools = \App\Models\Tool::with('categoryRelation')->active()->ordered()->get();
            return $tools->map(function ($tool) {
                // Format as object/array to match legacy expected output if needed, or return Model
                // Existing view code might expect Arrays or Objects with specific properties.
                // Tool types seem to use object syntax $tool->name in views (e.g. category pages).
                // ToolData::getToolBySlug output was cast to (object).
                // Eloquent Models are objects, so compatibility is high.
                // But we need to ensure 'category' property matches what views expect (slug vs relationship).
                // The 'category' column exists in tools table (varchar), so $tool->category returns the slug.
                return $tool;
            });
        });
    }

    /**
     * Get tool by slug from Database (Cached)
     */
    public static function getToolBySlug($slug)
    {
        return \Illuminate\Support\Facades\Cache::remember("tool_{$slug}", 3600, function () use ($slug) {
            return \App\Models\Tool::where('slug', $slug)->active()->first();
        });
    }

    /**
     * Get Initial Data for Seeding (Legacy Array)
     */
    public static function getInitialToolsData()
    {
        return array_merge(
            self::getImageTools(),
            self::getNetworkTools(),
            self::getUtilityTools(),
            self::getYouTubeTools(),
            self::getTimeTools(),
            self::getSeoTools(),
            self::getSpreadsheetTools(),
            self::getDocumentTools(),
            self::getUnitConverterTools(),
        );
    }

    private static function getImageTools()
    {
        return [
            [
                'name' => 'Image Converter',
                'slug' => 'image-converter',
                'icon_name' => 'fa-solid fa-image',
                'category' => 'image',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.image-converter',
                'url' => '/tools/image-converter',
                'order' => 100,
            ],
            [
                'name' => 'JPG to PNG Converter',
                'slug' => 'jpg-to-png-converter',
                'icon_name' => 'fa-solid fa-file-image',
                'category' => 'image',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.jpg-to-png-converter',
                'url' => '/tools/jpg-to-png-converter',
                'order' => 101,
            ],
            [
                'name' => 'PNG to JPG Converter',
                'slug' => 'png-to-jpg-converter',
                'icon_name' => 'fa-solid fa-file-image',
                'category' => 'image',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.png-to-jpg-converter',
                'url' => '/tools/png-to-jpg-converter',
                'order' => 102,
            ],
            [
                'name' => 'JPG to WebP Converter',
                'slug' => 'jpg-to-webp-converter',
                'icon_name' => 'fa-solid fa-file-image',
                'category' => 'image',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.jpg-to-webp-converter',
                'url' => '/tools/jpg-to-webp-converter',
                'order' => 103,
            ],
            [
                'name' => 'WebP to JPG Converter',
                'slug' => 'webp-to-jpg-converter',
                'icon_name' => 'fa-solid fa-file-image',
                'category' => 'image',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.webp-to-jpg-converter',
                'url' => '/tools/webp-to-jpg-converter',
                'order' => 104,
            ],
            [
                'name' => 'HEIC to JPG Converter',
                'slug' => 'heic-to-jpg-converter',
                'icon_name' => 'fa-solid fa-file-image',
                'category' => 'image',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.heic-to-jpg-converter',
                'url' => '/tools/heic-to-jpg-converter',
                'order' => 105,
            ],
            [
                'name' => 'Image to Base64',
                'slug' => 'image-to-base64-converter',
                'icon_name' => 'fa-solid fa-code',
                'category' => 'image',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.image-to-base64-converter',
                'url' => '/tools/image-to-base64-converter',
                'order' => 106,
            ],
            [
                'name' => 'Base64 to Image',
                'slug' => 'base64-to-image-converter',
                'icon_name' => 'fa-solid fa-image',
                'category' => 'image',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.base64-to-image-converter',
                'url' => '/tools/base64-to-image-converter',
                'order' => 107,
            ],
            [
                'name' => 'PNG to WebP Converter',
                'slug' => 'png-to-webp-converter',
                'icon_name' => 'fa-solid fa-file-image',
                'category' => 'image',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.png-to-webp-converter',
                'url' => '/tools/png-to-webp-converter',
                'order' => 108,
            ],
            [
                'name' => 'SVG to PNG Converter',
                'slug' => 'svg-to-png-converter',
                'icon_name' => 'fa-solid fa-file-image',
                'category' => 'image',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.svg-to-png-converter',
                'url' => '/tools/svg-to-png-converter',
                'order' => 109,
            ],
            [
                'name' => 'SVG to JPG Converter',
                'slug' => 'svg-to-jpg-converter',
                'icon_name' => 'fa-solid fa-file-image',
                'category' => 'image',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.svg-to-jpg-converter',
                'url' => '/tools/svg-to-jpg-converter',
                'order' => 110,
            ],
            [
                'name' => 'ICO Converter',
                'slug' => 'ico-converter',
                'icon_name' => 'fa-solid fa-icons',
                'category' => 'image',
                'controller' => 'Tools\Utility\ImageToolsController',
                'route_name' => 'utility.ico-converter',
                'url' => '/tools/ico-converter',
                'order' => 111,
            ],
            [
                'name' => 'Image Compressor',
                'slug' => 'image-compressor',
                'icon_name' => 'fa-solid fa-compress',
                'category' => 'image',
                'controller' => 'Tools\Utility\ImageCompressorController',
                'route_name' => 'utility.image-compressor',
                'url' => '/tools/image-compressor',
                'order' => 5,
            ],
            [
                'name' => 'QR Code Generator',
                'slug' => 'qr-code-generator',
                'icon_name' => 'fa-solid fa-qrcode',
                'category' => 'utility',
                'controller' => 'Tools\Utility\QrGeneratorController',
                'route_name' => 'utility.qr-code-generator',
                'url' => '/tools/qr-code-generator',
                'order' => 14,
            ],
        ];
    }

    private static function getNetworkTools()
    {
        return [
            [
                'name' => 'What Is My IP',
                'slug' => 'what-is-my-ip',
                'icon_name' => 'fa-solid fa-globe',
                'category' => 'network',
                'controller' => 'Tools\Network\WhatIsMyIpController',
                'route_name' => 'network.what-is-my-ip',
                'url' => '/tools/what-is-my-ip',
                'order' => 1,
            ],
            [
                'name' => 'What Is My ISP',
                'slug' => 'what-is-my-isp',
                'icon_name' => 'fa-solid fa-server',
                'category' => 'network',
                'controller' => 'Tools\Network\WhatIsMyIspController',
                'route_name' => 'network.what-is-my-isp',
                'url' => '/tools/what-is-my-isp',
                'order' => 2,
            ],
            [
                'name' => 'Domain to IP',
                'slug' => 'domain-to-ip',
                'icon_name' => 'fa-solid fa-network-wired',
                'category' => 'network',
                'controller' => 'Tools\Network\DomainToIpController',
                'route_name' => 'network.domain-to-ip',
                'url' => '/tools/domain-to-ip',
                'order' => 3,
            ],
            [
                'name' => 'IP Lookup',
                'slug' => 'ip-lookup',
                'icon_name' => 'fa-solid fa-search',
                'category' => 'network',
                'controller' => 'Tools\Network\IpLookupController',
                'route_name' => 'network.ip-lookup',
                'url' => '/tools/ip-lookup',
                'order' => 33,
            ],
            [
                'name' => 'DNS Lookup',
                'slug' => 'dns-lookup',
                'icon_name' => 'fa-solid fa-search',
                'category' => 'network',
                'controller' => 'Tools\Network\DnsLookupController',
                'route_name' => 'network.dns-lookup',
                'url' => '/tools/dns-lookup',
                'order' => 34,
            ],
            [
                'name' => 'WHOIS Lookup',
                'slug' => 'whois-lookup',
                'icon_name' => 'fa-solid fa-search',
                'category' => 'network',
                'controller' => 'Tools\Network\WhoisLookupController',
                'route_name' => 'network.whois-lookup',
                'url' => '/tools/whois-lookup',
                'order' => 35,
            ],
            [
                'name' => 'Ping Test',
                'slug' => 'ping-test',
                'icon_name' => 'fa-solid fa-signal',
                'category' => 'network',
                'controller' => 'Tools\Network\PingTestController',
                'route_name' => 'network.ping-test',
                'url' => '/tools/ping-test',
                'order' => 36,
            ],
            [
                'name' => 'Traceroute',
                'slug' => 'traceroute',
                'icon_name' => 'fa-solid fa-route',
                'category' => 'network',
                'controller' => 'Tools\Network\TracerouteController',
                'route_name' => 'network.traceroute',
                'url' => '/tools/traceroute',
                'order' => 37,
            ],
            [
                'name' => 'Port Checker',
                'slug' => 'port-checker',
                'icon_name' => 'fa-solid fa-plug',
                'category' => 'network',
                'controller' => 'Tools\Network\PortCheckerController',
                'route_name' => 'network.port-checker',
                'url' => '/tools/port-checker',
                'order' => 38,
            ],
            [
                'name' => 'Reverse DNS Lookup',
                'slug' => 'reverse-dns',
                'icon_name' => 'fa-solid fa-exchange-alt',
                'category' => 'network',
                'controller' => 'Tools\Network\ReverseDnsController',
                'route_name' => 'network.reverse-dns',
                'url' => '/tools/reverse-dns',
                'order' => 39,
            ],
        ];
    }

    private static function getUtilityTools()
    {
        return [
            [
                'name' => 'Internet Speed Test',
                'slug' => 'internet-speed-test',
                'category' => 'utility',
                'controller' => 'Tools\Utility\InternetSpeedTestController',
                'route_name' => 'utility.speed-test',
                'url' => '/tools/internet-speed-test',
                'order' => 4,
            ],
            [
                'name' => 'RGB to HEX Converter',
                'slug' => 'rgb-hex-converter',
                'icon_name' => 'fa-solid fa-palette',
                'category' => 'utility',
                'controller' => 'Tools\Utility\RgbHexConverterController',
                'route_name' => 'utility.rgb-hex-converter',
                'url' => '/tools/rgb-hex-converter',
                'order' => 6,
            ],
            [
                'name' => 'Slug Generator',
                'slug' => 'slug-generator',
                'icon_name' => 'fa-solid fa-link',
                'category' => 'utility',
                'controller' => 'Tools\Utility\SlugGeneratorController',
                'route_name' => 'utility.slug-generator',
                'url' => '/tools/slug-generator',
                'order' => 7,
            ],
            [
                'name' => 'MD5 Generator',
                'slug' => 'md5-generator',
                'icon_name' => 'fa-solid fa-hashtag',
                'category' => 'utility',
                'controller' => 'Tools\Utility\Md5GeneratorController',
                'route_name' => 'utility.md5-generator',
                'url' => '/tools/md5-generator',
                'order' => 8,
            ],
            [
                'name' => 'Case Converter',
                'slug' => 'case-converter',
                'category' => 'utility',
                'controller' => 'Tools\Utility\CaseConverterController',
                'route_name' => 'utility.case-converter',
                'url' => '/tools/case-converter',
                'order' => 9,
            ],
            [
                'name' => 'Username Checker',
                'slug' => 'username-checker',
                'icon_name' => 'fa-solid fa-user-check',
                'category' => 'utility',
                'controller' => 'Tools\Utility\UsernameCheckerController',
                'route_name' => 'utility.username-checker',
                'url' => '/tools/username-checker',
                'order' => 10,
            ],
            [
                'name' => 'Password Generator',
                'slug' => 'password-generator',
                'icon_name' => 'fa-solid fa-key',
                'category' => 'utility',
                'controller' => 'Tools\Utility\PasswordGeneratorController',
                'route_name' => 'utility.password-generator',
                'url' => '/tools/password-generator',
                'order' => 11,
            ],
            [
                'name' => 'JSON Formatter',
                'slug' => 'json-formatter',
                'icon_name' => 'fa-solid fa-code',
                'category' => 'utility',
                'controller' => 'Tools\Utility\JsonFormatterController',
                'route_name' => 'utility.json-formatter',
                'url' => '/tools/json-formatter',
                'order' => 12,
            ],
            [
                'name' => 'Base64 Encoder/Decoder',
                'slug' => 'base64-encoder-decoder',
                'category' => 'utility',
                'controller' => 'Tools\Utility\Base64Controller',
                'route_name' => 'utility.base64-encoder-decoder',
                'url' => '/tools/base64-encoder-decoder',
                'order' => 13,
            ],
            [
                'name' => 'HTML Viewer',
                'slug' => 'html-viewer',
                'icon_name' => 'fa-solid fa-code',
                'category' => 'utility',
                'controller' => 'Tools\Utility\HtmlViewerController',
                'route_name' => 'utility.html-viewer',
                'url' => '/tools/html-viewer',
                'order' => 15,
            ],
            [
                'name' => 'JSON Parser',
                'slug' => 'json-parser',
                'icon_name' => 'fa-solid fa-code',
                'category' => 'utility',
                'controller' => 'Tools\Utility\JsonParserController',
                'route_name' => 'utility.json-parser',
                'url' => '/tools/json-parser',
                'order' => 16,
            ],
            [
                'name' => 'Code Formatter',
                'slug' => 'code-formatter',
                'icon_name' => 'fa-solid fa-code',
                'category' => 'utility',
                'controller' => 'Tools\Utility\CodeFormatterController',
                'route_name' => 'utility.code-formatter',
                'url' => '/tools/code-formatter',
                'order' => 27,
            ],
            [
                'name' => 'CSS Minifier',
                'slug' => 'css-minifier',
                'icon_name' => 'fa-solid fa-compress-alt',
                'category' => 'utility',
                'controller' => 'Tools\Utility\CssMinifierController',
                'route_name' => 'utility.css-minifier',
                'url' => '/tools/css-minifier',
                'order' => 27,
            ],
            [
                'name' => 'JavaScript Minifier',
                'slug' => 'js-minifier',
                'icon_name' => 'fa-solid fa-compress-alt',
                'category' => 'utility',
                'controller' => 'Tools\Utility\JsMinifierController',
                'route_name' => 'utility.js-minifier',
                'url' => '/tools/js-minifier',
                'order' => 28,
            ],
            [
                'name' => 'HTML Minifier',
                'slug' => 'html-minifier',
                'icon_name' => 'fa-solid fa-compress-alt',
                'category' => 'utility',
                'controller' => 'Tools\Utility\HtmlMinifierController',
                'route_name' => 'utility.html-minifier',
                'url' => '/tools/html-minifier',
                'order' => 29,
            ],
            [
                'slug' => 'ascii-converter',
                'icon_name' => 'fa-solid fa-exchange-alt',
                'name' => 'ASCII Converter',
                'category' => 'utility',
                'controller' => 'EncodingController@asciiConvert',
                'route_name' => 'utility.ascii-converter',
                'url' => '/tools/ascii-converter',
                'order' => 34,
            ],
            [
                'slug' => 'binary-hex-converter',
                'icon_name' => 'fa-solid fa-exchange-alt',
                'name' => 'Binary to Hexadecimal Converter',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\BinaryHexController',
                'route_name' => 'utility.binary-hex-converter',
                'url' => '/tools/binary-hex-converter',
                'order' => 69,
            ],
            [
                'slug' => 'camel-case-converter',
                'icon_name' => 'fa-solid fa-font',
                'name' => 'Camel Case Converter',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\CamelCaseController',
                'route_name' => 'utility.camel-case-converter',
                'url' => '/tools/camel-case-converter',
                'order' => 49,
            ],
            [
                'slug' => 'csv-to-xml-converter',
                'name' => 'CSV to XML Converter',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\CsvXmlController',
                'route_name' => 'utility.csv-to-xml-converter',
                'url' => '/tools/csv-to-xml-converter',
                'order' => 37,
            ],
            [
                'slug' => 'decimal-binary-converter',
                'icon_name' => 'fa-solid fa-exchange-alt',
                'name' => 'Decimal to Binary Converter',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\DecimalBinaryController',
                'route_name' => 'utility.decimal-binary-converter',
                'url' => '/tools/decimal-binary-converter',
                'order' => 67,
            ],
            [
                'slug' => 'decimal-hex-converter',
                'icon_name' => 'fa-solid fa-exchange-alt',
                'name' => 'Decimal to Hexadecimal Converter',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\DecimalHexController',
                'route_name' => 'utility.decimal-hex-converter',
                'url' => '/tools/decimal-hex-converter',
                'order' => 68,
            ],
            [
                'slug' => 'decimal-octal-converter',
                'icon_name' => 'fa-solid fa-exchange-alt',
                'name' => 'Decimal to Octal Converter',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\DecimalOctalController',
                'route_name' => 'utility.decimal-octal-converter',
                'url' => '/tools/decimal-octal-converter',
                'order' => 70,
            ],
            [
                'slug' => 'html-encoder-decoder',
                'name' => 'HTML Encoder/Decoder',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\HtmlEncoderController',
                'route_name' => 'utility.html-encoder-decoder',
                'url' => '/tools/html-encoder-decoder',
                'order' => 31,
            ],
            [
                'slug' => 'html-to-markdown-converter',
                'name' => 'HTML to Markdown Converter',
                'category' => 'utility',
                'controller' => 'ConverterController@htmlToMarkdown',
                'route_name' => 'utility.html-to-markdown-converter',
                'url' => '/tools/html-to-markdown-converter',
                'order' => 45,
            ],
            [
                'slug' => 'json-to-sql-converter',
                'name' => 'JSON to SQL Converter',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\JsonSqlController',
                'route_name' => 'utility.json-to-sql-converter',
                'url' => '/tools/json-to-sql-converter',
                'order' => 38,
            ],
            [
                'slug' => 'json-to-xml-converter',
                'name' => 'JSON to XML Converter',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\JsonXmlController',
                'route_name' => 'utility.json-to-xml-converter',
                'url' => '/tools/json-to-xml-converter',
                'order' => 35,
            ],
            [
                'slug' => 'json-to-yaml-converter',
                'name' => 'JSON to YAML Converter',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\JsonYamlController',
                'route_name' => 'utility.json-to-yaml-converter',
                'url' => '/tools/json-to-yaml-converter',
                'order' => 36,
            ],
            [
                'slug' => 'jwt-decoder',
                'icon_name' => 'fa-solid fa-unlock',
                'name' => 'JWT Decoder',
                'category' => 'utility',
                'controller' => 'EncodingController@jwtDecode',
                'route_name' => 'utility.jwt-decoder',
                'url' => '/tools/jwt-decoder',
                'order' => 33,
            ],
            [
                'slug' => 'kebab-case-converter',
                'icon_name' => 'fa-solid fa-font',
                'name' => 'Kebab Case Converter',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\KebabCaseController',
                'route_name' => 'utility.kebab-case-converter',
                'url' => '/tools/kebab-case-converter',
                'order' => 52,
            ],
            [
                'slug' => 'markdown-to-html-converter',
                'name' => 'Markdown to HTML Converter',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\MarkdownToHtmlController',
                'route_name' => 'utility.markdown-to-html-converter',
                'url' => '/tools/markdown-to-html-converter',
                'order' => 44,
            ],
            [
                'slug' => 'morse-to-text-converter',
                'icon_name' => 'fa-solid fa-exchange-alt',
                'name' => 'Morse Code to Text',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\MorseToTextController',
                'route_name' => 'utility.morse-to-text-converter',
                'url' => '/tools/morse-to-text-converter',
                'order' => 56,
            ],
            [
                'slug' => 'number-base-converter',
                'icon_name' => 'fa-solid fa-calculator',
                'name' => 'Number Base Converter',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\NumberBaseController',
                'route_name' => 'utility.number-base-converter',
                'url' => '/tools/number-base-converter',
                'order' => 71,
            ],
            [
                'slug' => 'pascal-case-converter',
                'icon_name' => 'fa-solid fa-font',
                'name' => 'Pascal Case Converter',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\PascalCaseController',
                'route_name' => 'utility.pascal-case-converter',
                'url' => '/tools/pascal-case-converter',
                'order' => 50,
            ],
            [
                'slug' => 'sentence-case-converter',
                'icon_name' => 'fa-solid fa-font',
                'name' => 'Sentence Case Converter',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\SentenceCaseController',
                'route_name' => 'utility.sentence-case-converter',
                'url' => '/tools/sentence-case-converter',
                'order' => 48,
            ],
            [
                'slug' => 'snake-case-converter',
                'icon_name' => 'fa-solid fa-font',
                'name' => 'Snake Case Converter',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\SnakeCaseController',
                'route_name' => 'utility.snake-case-converter',
                'url' => '/tools/snake-case-converter',
                'order' => 51,
            ],
            [
                'slug' => 'studly-case-converter',
                'icon_name' => 'fa-solid fa-font',
                'name' => 'Studly Case Converter',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\StudlyCaseController',
                'route_name' => 'utility.studly-case-converter',
                'url' => '/tools/studly-case-converter',
                'order' => 53,
            ],
            [
                'slug' => 'text-reverser',
                'icon_name' => 'text-reverser',
                'name' => 'Text Reverser',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\TextReverserController',
                'route_name' => 'utility.text-reverser',
                'url' => '/tools/text-reverser',
                'order' => 54,
            ],
            [
                'slug' => 'text-to-morse-converter',
                'icon_name' => 'fa-solid fa-exchange-alt',
                'name' => 'Text to Morse Code',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\TextToMorseController',
                'route_name' => 'utility.text-to-morse-converter',
                'url' => '/tools/text-to-morse-converter',
                'order' => 55,
            ],
            [
                'slug' => 'tsv-to-csv-converter',
                'name' => 'TSV to CSV Converter',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\TsvCsvController',
                'route_name' => 'utility.tsv-to-csv-converter',
                'url' => '/tools/tsv-to-csv-converter',
                'order' => 39,
            ],
            [
                'slug' => 'unicode-encoder-decoder',
                'icon_name' => 'unicode-encoder-decoder',
                'name' => 'Unicode Encoder/Decoder',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\UnicodeEncoderController',
                'route_name' => 'utility.unicode-encoder-decoder',
                'url' => '/tools/unicode-encoder-decoder',
                'order' => 32,
            ],
            [
                'slug' => 'url-encoder-decoder',
                'name' => 'URL Encoder/Decoder',
                'category' => 'utility',
                'controller' => 'Tools\\Utility\\UrlEncoderController',
                'route_name' => 'utility.url-encoder-decoder',
                'url' => '/tools/url-encoder-decoder',
                'order' => 30,
            ],
            [
                'name' => 'Lorem Ipsum Generator',
                'slug' => 'lorem-ipsum-generator',
                'icon_name' => 'lorem-ipsum-generator',
                'description' => 'Generate standard Lorem Ipsum placeholder text.',
                'category' => 'utility',
                'controller' => 'Tools\Utility\LoremIpsumGeneratorController',
                'route_name' => 'utility.lorem-ipsum-generator',
                'url' => '/tools/lorem-ipsum-generator',
                'order' => 170,
            ],
            [
                'name' => 'Random Number Generator',
                'slug' => 'random-number-generator',
                'icon_name' => 'fa-solid fa-random',
                'description' => 'Generate random numbers within a specified range.',
                'category' => 'utility',
                'controller' => 'Tools\Utility\RandomNumberGeneratorController',
                'route_name' => 'utility.random-number-generator',
                'url' => '/tools/random-number-generator',
                'order' => 171,
            ],
            [
                'name' => 'UUID/GUID Generator',
                'slug' => 'uuid-generator',
                'icon_name' => 'uuid-generator',
                'description' => 'Generate random version 4 UUIDs/GUIDs.',
                'category' => 'utility',
                'controller' => 'Tools\Utility\UuidGeneratorController',
                'route_name' => 'utility.uuid-generator',
                'url' => '/tools/uuid-generator',
                'order' => 172,
            ],
            [
                'name' => 'Duplicate Line Remover',
                'slug' => 'duplicate-line-remover',
                'icon_name' => 'duplicate-line-remover',
                'description' => 'Remove duplicate lines from text lists instantly.',
                'category' => 'utility',
                'controller' => 'Tools\Utility\DuplicateRemoverController',
                'route_name' => 'utility.duplicate-line-remover',
                'url' => '/tools/duplicate-line-remover',
                'order' => 173,
            ],
            [
                'name' => 'XML Formatter',
                'slug' => 'xml-formatter',
                'icon_name' => 'xml-formatter',
                'description' => 'Format and beautify XML code.',
                'category' => 'utility',
                'controller' => 'Tools\Utility\XmlFormatterController',
                'route_name' => 'utility.xml-formatter',
                'url' => '/tools/xml-formatter',
                'order' => 174,
            ],
            [
                'name' => 'Diff Checker',
                'slug' => 'diff-checker',
                'icon_name' => 'diff-checker',
                'description' => 'Compare two text files to find differences.',
                'category' => 'utility',
                'controller' => 'Tools\Utility\DiffCheckerController',
                'route_name' => 'utility.diff-checker',
                'url' => '/tools/diff-checker',
                'order' => 175,
            ],
            [
                'name' => 'Cron Job Generator',
                'slug' => 'cron-job-generator',
                'icon_name' => 'cron-job-generator',
                'description' => 'Create cron schedules with a GUI.',
                'category' => 'utility',
                'controller' => 'Tools\Utility\CronJobGeneratorController',
                'route_name' => 'utility.cron-job-generator',
                'url' => '/tools/cron-job-generator',
                'order' => 176,
            ],
            [
                'name' => 'User Agent Parser',
                'slug' => 'user-agent-parser',
                'icon_name' => 'user-agent-parser',
                'description' => 'Parse and explain User-Agent strings.',
                'category' => 'utility',
                'controller' => 'Tools\Utility\UserAgentParserController',
                'route_name' => 'utility.user-agent-parser',
                'url' => '/tools/user-agent-parser',
                'order' => 177,
            ],
            [
                'name' => 'Curl Command Builder',
                'slug' => 'curl-command-builder',
                'icon_name' => 'curl-command-builder',
                'description' => 'Build Curl commands with a visual interface.',
                'category' => 'utility',
                'controller' => 'Tools\Utility\CurlBuilderController',
                'route_name' => 'utility.curl-command-builder',
                'url' => '/tools/curl-command-builder',
                'order' => 178,
            ],
        ];
    }

    private static function getYouTubeTools()
    {
        return [
            [
                'name' => 'YouTube Monetization Checker',
                'slug' => 'youtube-monetization-checker',
                'icon_name' => 'youtube-monetization-checker',
                'category' => 'youtube',
                'controller' => 'Tools\YouTube\MonetizationCheckerController',
                'route_name' => 'youtube.youtube-monetization-checker',
                'url' => '/tools/youtube-monetization-checker',
                'order' => 17,
            ],
            [
                'name' => 'YouTube Thumbnail Downloader',
                'slug' => 'youtube-thumbnail-downloader',
                'icon_name' => 'youtube-thumbnail-downloader',
                'category' => 'youtube',
                'controller' => 'Tools\YouTube\ThumbnailDownloaderController',
                'route_name' => 'youtube.youtube-thumbnail-downloader',
                'url' => '/tools/youtube-thumbnail-downloader',
                'order' => 18,
            ],
            [
                'name' => 'YouTube Video Data Extractor',
                'slug' => 'youtube-video-data-extractor',
                'icon_name' => 'youtube-video-data-extractor',
                'category' => 'youtube',
                'controller' => 'Tools\YouTube\VideoDataExtractorController',
                'route_name' => 'youtube.youtube-video-data-extractor',
                'url' => '/tools/youtube-video-data-extractor',
                'order' => 19,
            ],
            [
                'name' => 'YouTube Tags Generator',
                'slug' => 'youtube-tag-generator',
                'icon_name' => 'youtube-tag-generator',
                'category' => 'youtube',
                'controller' => 'Tools\YouTube\TagsGeneratorController',
                'route_name' => 'youtube.youtube-tag-generator',
                'url' => '/tools/youtube-tag-generator',
                'order' => 20,
            ],
            [
                'name' => 'YouTube Channel Data Extractor',
                'slug' => 'youtube-channel-data-extractor',
                'icon_name' => 'youtube-channel-data-extractor',
                'category' => 'youtube',
                'controller' => 'Tools\YouTube\ChannelDataExtractorController',
                'route_name' => 'youtube.youtube-channel-data-extractor',
                'url' => '/tools/youtube-channel-data-extractor',
                'order' => 21,
            ],
            [
                'name' => 'YouTube Handle Checker',
                'slug' => 'youtube-handle-checker',
                'icon_name' => 'youtube-handle-checker',
                'category' => 'youtube',
                'controller' => 'Tools\YouTube\HandleCheckerController',
                'route_name' => 'youtube.youtube-handle-checker',
                'url' => '/tools/youtube-handle-checker',
                'order' => 22,
            ],
            [
                'name' => 'YouTube Video Tags Extractor',
                'slug' => 'youtube-video-tags-extractor',
                'icon_name' => 'youtube-video-tags-extractor',
                'category' => 'youtube',
                'controller' => 'Tools\YouTube\VideoTagsExtractorController',
                'route_name' => 'youtube.youtube-video-tags-extractor',
                'url' => '/tools/youtube-video-tags-extractor',
                'order' => 30,
            ],
            [
                'name' => 'YouTube Channel ID Finder',
                'slug' => 'youtube-channel-id-finder',
                'icon_name' => 'youtube-channel-id-finder',
                'category' => 'youtube',
                'controller' => 'Tools\YouTube\ChannelIdFinderController',
                'route_name' => 'youtube.youtube-channel-id-finder',
                'url' => '/tools/youtube-channel-id-finder',
                'order' => 31,
            ],
            [
                'name' => 'YouTube Earnings Calculator',
                'slug' => 'youtube-earnings-calculator',
                'icon_name' => 'youtube-earnings-calculator',
                'category' => 'youtube',
                'controller' => 'Tools\YouTube\EarningsCalculatorController',
                'route_name' => 'youtube.youtube-earnings-calculator',
                'url' => '/tools/youtube-earnings-calculator',
                'order' => 32,
            ],
            [
                'name' => 'Text to Speech',
                'slug' => 'text-to-speech',
                'icon_name' => 'volume-high',
                'category' => 'youtube',
                'controller' => 'Tools\Youtube\TextToSpeechController',
                'route_name' => 'youtube.text-to-speech',
                'url' => '/tools/text-to-speech',
                'order' => 33,
            ],
        ];
    }



    private static function getSeoTools()
    {
        return [
            [
                'name' => 'Meta Tag Analyzer',
                'slug' => 'meta-tag-analyzer',
                'category' => 'seo',
                'controller' => 'Tools\Seo\MetaTagAnalyzerController',
                'route_name' => 'seo.meta-tag-analyzer',
                'url' => '/tools/meta-tag-analyzer',
                'order' => 23,
            ],
            [
                'name' => 'Keyword Density Checker',
                'slug' => 'keyword-density-checker',
                'category' => 'seo',
                'controller' => 'Tools\Seo\KeywordDensityCheckerController',
                'route_name' => 'seo.keyword-density-checker',
                'url' => '/tools/keyword-density-checker',
                'order' => 24,
            ],
            [
                'name' => 'Word Counter',
                'slug' => 'word-counter',
                'icon_name' => 'word-counter',
                'category' => 'seo',
                'controller' => 'Tools\Text\WordCounterController',
                'route_name' => 'text.word-counter',
                'url' => '/tools/word-counter',
                'order' => 25,
            ],
            [
                'name' => 'Redirect & HTTP Status Checker',
                'slug' => 'redirect-checker',
                'icon_name' => 'redirect-checker',
                'category' => 'seo',
                'controller' => 'Tools\Seo\RedirectCheckerController',
                'route_name' => 'seo.redirect-checker',
                'url' => '/tools/redirect-checker',
                'order' => 26,
            ],
            [
                'slug' => 'bing-serp-checker',
                'icon_name' => 'bing-serp-checker',
                'name' => 'Bing SERP Checker',
                'category' => 'seo',
                'controller' => 'Tools\\Seo\\BingSerpCheckerController',
                'route_name' => 'seo.bing-serp-checker',
                'url' => '/tools/bing-serp-checker',
                'order' => 15,
            ],
            [
                'slug' => 'broken-links-checker',
                'icon_name' => 'broken-links-checker',
                'name' => 'Broken Links Checker',
                'category' => 'seo',
                'controller' => 'Tools\\Seo\\BrokenLinksCheckerController',
                'route_name' => 'seo.broken-links-checker',
                'url' => '/tools/broken-links-checker',
                'order' => 18,
            ],
            [
                'slug' => 'google-serp-checker',
                'icon_name' => 'google-serp-checker',
                'name' => 'Google SERP Checker',
                'category' => 'seo',
                'controller' => 'Tools\\Seo\\GoogleSerpCheckerController',
                'route_name' => 'seo.google-serp-checker',
                'url' => '/tools/google-serp-checker',
                'order' => 14,
            ],
            [
                'slug' => 'on-page-seo-checker',
                'icon_name' => 'on-page-seo-checker',
                'name' => 'On-Page SEO Checker',
                'category' => 'seo',
                'controller' => 'Tools\\Seo\\OnPageSeoCheckerController',
                'route_name' => 'seo.on-page-seo-checker',
                'url' => '/tools/on-page-seo-checker',
                'order' => 17,
            ],
            [
                'slug' => 'yahoo-serp-checker',
                'icon_name' => 'yahoo-serp-checker',
                'name' => 'Yahoo SERP Checker',
                'category' => 'seo',
                'controller' => 'Tools\\Seo\\YahooSerpCheckerController',
                'route_name' => 'seo.yahoo-serp-checker',
                'url' => '/tools/yahoo-serp-checker',
                'order' => 16,
            ],
            [
                'name' => 'Hreflang Checker',
                'slug' => 'hreflang-checker',
                'icon_name' => 'fa-solid fa-language',
                'category' => 'seo',
                'controller' => 'Tools\Seo\HreflangCheckerController',
                'route_name' => 'seo.hreflang-checker',
                'url' => '/tools/hreflang-checker',
                'order' => 27,
            ],
            [
                'name' => 'Google Index Checker',
                'slug' => 'google-index-checker',
                'icon_name' => 'fa-solid fa-magnifying-glass',
                'category' => 'seo',
                'controller' => 'Tools\Seo\GoogleIndexCheckerController',
                'route_name' => 'seo.google-index-checker',
                'url' => '/tools/google-index-checker',
                'order' => 28,
            ],
        ];
    }

    private static function getSpreadsheetTools()
    {
        return [
            [
                'name' => 'Excel to CSV Converter',
                'slug' => 'excel-to-csv',
                'icon_name' => 'excel-to-csv',
                'category' => 'utility',
                'controller' => 'SpreadsheetConverterController',
                'route_name' => 'utility.excel-to-csv',
                'url' => '/tools/excel-to-csv',
                'order' => 150,
            ],
            [
                'name' => 'CSV to Excel Converter',
                'slug' => 'csv-to-excel',
                'icon_name' => 'csv-to-excel',
                'category' => 'utility',
                'controller' => 'SpreadsheetConverterController',
                'route_name' => 'utility.csv-to-excel',
                'url' => '/tools/csv-to-excel',
                'order' => 151,
            ],
            [
                'name' => 'XLS to XLSX Converter',
                'slug' => 'xls-to-xlsx',
                'icon_name' => 'xls-to-xlsx',
                'category' => 'utility',
                'controller' => 'SpreadsheetConverterController',
                'route_name' => 'utility.xls-to-xlsx',
                'url' => '/tools/xls-to-xlsx',
                'order' => 152,
            ],
            [
                'name' => 'XLSX to XLS Converter',
                'slug' => 'xlsx-to-xls',
                'icon_name' => 'xlsx-to-xls',
                'category' => 'utility',
                'controller' => 'SpreadsheetConverterController',
                'route_name' => 'utility.xlsx-to-xls',
                'url' => '/tools/xlsx-to-xls',
                'order' => 153,
            ],
            [
                'name' => 'Google Sheets to Excel',
                'slug' => 'google-sheets-to-excel',
                'icon_name' => 'google-sheets-to-excel',
                'category' => 'utility',
                'controller' => 'SpreadsheetConverterController',
                'route_name' => 'utility.google-sheets-to-excel',
                'url' => '/tools/google-sheets-to-excel',
                'order' => 154,
            ],
            [
                'name' => 'CSV to SQL Converter',
                'slug' => 'csv-to-sql',
                'icon_name' => 'csv-to-sql',
                'category' => 'utility',
                'controller' => 'SpreadsheetConverterController',
                'route_name' => 'utility.csv-to-sql',
                'url' => '/tools/csv-to-sql',
                'order' => 155,
            ],

        ];
    }

    private static function getDocumentTools()
    {
        return [
            [
                'name' => 'PDF to Word Converter',
                'slug' => 'pdf-to-word',
                'icon_name' => 'pdf-to-word',
                'description' => 'Convert PDF documents to editable Microsoft Word (DOC/DOCX) files.',
                'category' => 'utility',
                'controller' => 'App\Http\Controllers\Tools\Utility\DocumentConverterController',
                'route_name' => 'utility.pdf-to-word',
                'url' => '/tools/pdf-to-word',
                'order' => 120,
            ],
            [
                'name' => 'Word to PDF Converter',
                'slug' => 'word-to-pdf',
                'icon_name' => 'word-to-pdf',
                'description' => 'Convert Microsoft Word (DOC/DOCX) documents to PDF format.',
                'category' => 'utility',
                'controller' => 'App\Http\Controllers\Tools\Utility\DocumentConverterController',
                'route_name' => 'utility.word-to-pdf',
                'url' => '/tools/word-to-pdf',
                'order' => 121,
            ],
            [
                'name' => 'PDF to Excel Converter',
                'slug' => 'pdf-to-excel',
                'icon_name' => 'pdf-to-excel',
                'description' => 'Convert PDF tables to editable Microsoft Excel (XLS/XLSX) spreadsheets.',
                'category' => 'utility',
                'controller' => 'App\Http\Controllers\Tools\Utility\DocumentConverterController',
                'route_name' => 'utility.pdf-to-excel',
                'url' => '/tools/pdf-to-excel',
                'order' => 122,
            ],
            [
                'name' => 'Excel to PDF Converter',
                'slug' => 'excel-to-pdf',
                'icon_name' => 'excel-to-pdf',
                'description' => 'Convert Microsoft Excel (XLS/XLSX) spreadsheets to PDF format.',
                'category' => 'utility',
                'controller' => 'App\Http\Controllers\Tools\Utility\DocumentConverterController',
                'route_name' => 'utility.excel-to-pdf',
                'url' => '/tools/excel-to-pdf',
                'order' => 123,
            ],
            [
                'name' => 'PowerPoint to PDF Converter',
                'slug' => 'ppt-to-pdf',
                'description' => 'Convert Microsoft PowerPoint (PPT/PPTX) presentations to PDF format.',
                'category' => 'utility',
                'controller' => 'App\Http\Controllers\Tools\Utility\DocumentConverterController',
                'route_name' => 'utility.ppt-to-pdf',
                'url' => '/tools/ppt-to-pdf',
                'order' => 124,
            ],
            [
                'name' => 'PDF to PowerPoint Converter',
                'slug' => 'pdf-to-ppt',
                'description' => 'Convert PDF documents to editable Microsoft PowerPoint (PPT/PPTX) slides.',
                'category' => 'utility',
                'controller' => 'App\Http\Controllers\Tools\Utility\DocumentConverterController',
                'route_name' => 'utility.pdf-to-ppt',
                'url' => '/tools/pdf-to-ppt',
                'order' => 125,
            ],
            [
                'name' => 'PDF to JPG Converter',
                'slug' => 'pdf-to-jpg',
                'icon_name' => 'pdf-to-jpg',
                'description' => 'Convert PDF pages to high-quality JPG images.',
                'category' => 'utility',
                'controller' => 'App\Http\Controllers\Tools\Utility\DocumentConverterController',
                'route_name' => 'utility.pdf-to-jpg',
                'url' => '/tools/pdf-to-jpg',
                'order' => 126,
            ],
            [
                'name' => 'JPG to PDF Converter',
                'slug' => 'jpg-to-pdf',
                'icon_name' => 'jpg-to-pdf',
                'description' => 'Convert JPG images to PDF format.',
                'category' => 'utility',
                'controller' => 'App\Http\Controllers\Tools\Utility\DocumentConverterController',
                'route_name' => 'utility.jpg-to-pdf',
                'url' => '/tools/jpg-to-pdf',
                'order' => 127,
            ],
            [
                'name' => 'PDF Compressor',
                'slug' => 'pdf-compressor',
                'icon_name' => 'pdf-compressor',
                'description' => 'Compress PDF files to reduce file size without losing quality.',
                'category' => 'utility',
                'controller' => 'App\Http\Controllers\Tools\Utility\DocumentConverterController',
                'route_name' => 'utility.pdf-compressor',
                'url' => '/tools/pdf-compressor',
                'order' => 128,
            ],
            [
                'name' => 'PDF Merger',
                'slug' => 'pdf-merger',
                'icon_name' => 'pdf-merger',
                'description' => 'Combine multiple PDF files into one single document.',
                'category' => 'utility',
                'controller' => 'App\Http\Controllers\Tools\Utility\DocumentConverterController',
                'route_name' => 'utility.pdf-merger',
                'url' => '/tools/pdf-merger',
                'order' => 129,
            ],
            [
                'name' => 'PDF Splitter',
                'slug' => 'pdf-splitter',
                'icon_name' => 'pdf-splitter',
                'description' => 'Split a PDF file into multiple separate documents.',
                'category' => 'utility',
                'controller' => 'App\Http\Controllers\Tools\Utility\DocumentConverterController',
                'route_name' => 'utility.pdf-splitter',
                'url' => '/tools/pdf-splitter',
                'order' => 130,
            ],
        ];
    }

    private static function getTimeTools()
    {
        return [
            [
                'name' => 'Time Zone Converter',
                'slug' => 'time-zone-converter',
                'icon_name' => 'time-zone-converter',
                'description' => 'Convert time instantly between any global time zones.',
                'category' => 'utility',
                'controller' => 'App\Http\Controllers\Tools\Utility\TimeConverterController',
                'route_name' => 'utility.time-zone-converter',
                'url' => '/tools/time-zone-converter',
                'order' => 160,
            ],
            [
                'name' => 'Epoch Time Converter',
                'slug' => 'epoch-time-converter',
                'icon_name' => 'epoch-time-converter',
                'description' => 'Convert Unix timestamps to human-readable dates and vice versa.',
                'category' => 'utility',
                'controller' => 'App\Http\Controllers\Tools\Utility\TimeConverterController',
                'route_name' => 'utility.epoch-time-converter',
                'url' => '/tools/epoch-time-converter',
                'order' => 161,
            ],
            [
                'name' => 'Unix Timestamp to Date',
                'slug' => 'unix-timestamp-to-date',
                'description' => 'Convert numeric Unix timestamps to readable date and time formats.',
                'category' => 'utility',
                'controller' => 'App\Http\Controllers\Tools\Utility\TimeConverterController',
                'route_name' => 'utility.unix-timestamp-to-date',
                'url' => '/tools/unix-timestamp-to-date',
                'order' => 162,
            ],
            [
                'name' => 'Date to Unix Timestamp',
                'slug' => 'date-to-unix-timestamp',
                'description' => 'Convert any date and time to a Unix Epoch timestamp.',
                'category' => 'utility',
                'controller' => 'App\Http\Controllers\Tools\Utility\TimeConverterController',
                'route_name' => 'utility.date-to-unix-timestamp',
                'url' => '/tools/date-to-unix-timestamp',
                'order' => 163,
            ],
            [
                'name' => 'UTC to Local Time',
                'slug' => 'utc-to-local-time',
                'description' => 'Convert Universal Time Coordinated (UTC) to your local time.',
                'category' => 'utility',
                'controller' => 'App\Http\Controllers\Tools\Utility\TimeConverterController',
                'route_name' => 'utility.utc-to-local-time',
                'url' => '/tools/utc-to-local-time',
                'order' => 164,
            ],
            [
                'name' => 'Local Time to UTC',
                'slug' => 'local-time-to-utc',
                'description' => 'Convert your local time to Coordinated Universal Time (UTC).',
                'category' => 'utility',
                'controller' => 'App\Http\Controllers\Tools\Utility\TimeConverterController',
                'route_name' => 'utility.local-time-to-utc',
                'url' => '/tools/local-time-to-utc',
                'order' => 165,
            ],
        ];
    }

    private static function getUnitConverterTools()
    {
        return [
            // Batch A: Basic
            [
                'name' => 'Length Converter',
                'slug' => 'length-converter',
                'description' => 'Convert between length units (mm, cm, m, km, in, ft, yd, mi).',
                'category' => 'utility',
                'controller' => 'Tools\Converters\UnitConverterController',
                'route_name' => 'utility.length-converter',
                'url' => '/tools/length-converter',
                'icon_name' => 'length-converter',
                'order' => 200,
            ],
            [
                'name' => 'Weight Converter',
                'slug' => 'weight-converter',
                'description' => 'Convert between weight units (mg, g, kg, lb, oz, ton).',
                'category' => 'utility',
                'controller' => 'Tools\Converters\UnitConverterController',
                'route_name' => 'utility.weight-converter',
                'url' => '/tools/weight-converter',
                'icon_name' => 'weight-converter',
                'order' => 201,
            ],
            [
                'name' => 'Temperature Converter',
                'slug' => 'temperature-converter',
                'description' => 'Convert between Celsius, Fahrenheit, and Kelvin.',
                'category' => 'utility',
                'controller' => 'Tools\Converters\UnitConverterController',
                'route_name' => 'utility.temperature-converter',
                'url' => '/tools/temperature-converter',
                'icon_name' => 'temperature-converter',
                'order' => 202,
            ],
            [
                'name' => 'Volume Converter',
                'slug' => 'volume-converter',
                'description' => 'Convert volume units (ml, l, gal, qt, cup, etc).',
                'category' => 'utility',
                'controller' => 'Tools\Converters\UnitConverterController',
                'route_name' => 'utility.volume-converter',
                'url' => '/tools/volume-converter',
                'icon_name' => 'volume-converter',
                'order' => 203,
            ],
            [
                'name' => 'Area Converter',
                'slug' => 'area-converter',
                'description' => 'Convert area units (sq m, sq ft, acre, hectare).',
                'category' => 'utility',
                'controller' => 'Tools\Converters\UnitConverterController',
                'route_name' => 'utility.area-converter',
                'url' => '/tools/area-converter',
                'icon_name' => 'area-converter',
                'order' => 204,
            ],

            // Batch B: Scientific
            [
                'name' => 'Speed Converter',
                'slug' => 'speed-converter',
                'description' => 'Convert speed units (mph, kph, m/s, knot).',
                'category' => 'utility',
                'controller' => 'Tools\Converters\UnitConverterController',
                'route_name' => 'utility.speed-converter',
                'url' => '/tools/speed-converter',
                'icon_name' => 'speed-converter',
                'order' => 205,
            ],
            [
                'name' => 'Time Unit Converter',
                'slug' => 'time-unit-converter',
                'description' => 'Convert time units (sec, min, hr, day, year).',
                'category' => 'utility',
                'controller' => 'Tools\Converters\UnitConverterController',
                'route_name' => 'utility.time-unit-converter',
                'url' => '/tools/time-unit-converter',
                'icon_name' => 'time-unit-converter',
                'order' => 206,
            ],
            [
                'name' => 'Digital Storage Converter',
                'slug' => 'digital-storage-converter',
                'description' => 'Convert storage units (Bit, Byte, KB, MB, GB, TB).',
                'category' => 'utility',
                'controller' => 'Tools\Converters\UnitConverterController',
                'route_name' => 'utility.digital-storage-converter',
                'url' => '/tools/digital-storage-converter',
                'icon_name' => 'digital-storage-converter',
                'order' => 207,
            ],
            [
                'name' => 'Energy Converter',
                'slug' => 'energy-converter',
                'description' => 'Convert energy units (Joule, Calorie, kWh, BTU).',
                'category' => 'utility',
                'controller' => 'Tools\Converters\UnitConverterController',
                'route_name' => 'utility.energy-converter',
                'url' => '/tools/energy-converter',
                'icon_name' => 'energy-converter',
                'order' => 208,
            ],
            [
                'name' => 'Pressure Converter',
                'slug' => 'pressure-converter',
                'description' => 'Convert pressure units (Pascal, Bar, PSI, atm).',
                'category' => 'utility',
                'controller' => 'Tools\Converters\UnitConverterController',
                'route_name' => 'utility.pressure-converter',
                'url' => '/tools/pressure-converter',
                'icon_name' => 'pressure-converter',
                'order' => 209,
            ],

            // Batch C: Engineering
            [
                'name' => 'Power Converter',
                'slug' => 'power-converter',
                'description' => 'Convert power units (Watt, HP, kW).',
                'category' => 'utility',
                'controller' => 'Tools\Converters\UnitConverterController',
                'route_name' => 'utility.power-converter',
                'url' => '/tools/power-converter',
                'icon_name' => 'power-converter',
                'order' => 210,
            ],
            [
                'name' => 'Force Converter',
                'slug' => 'force-converter',
                'description' => 'Convert force units (Newton, Dyne, Pound-force).',
                'category' => 'utility',
                'controller' => 'Tools\Converters\UnitConverterController',
                'route_name' => 'utility.force-converter',
                'url' => '/tools/force-converter',
                'icon_name' => 'force-converter',
                'order' => 211,
            ],
            [
                'name' => 'Angle Converter',
                'slug' => 'angle-converter',
                'description' => 'Convert angle units (Degree, Radian, Gradian).',
                'category' => 'utility',
                'controller' => 'Tools\Converters\UnitConverterController',
                'route_name' => 'utility.angle-converter',
                'url' => '/tools/angle-converter',
                'icon_name' => 'angle-converter',
                'order' => 212,
            ],
            [
                'name' => 'Fuel Consumption Converter',
                'slug' => 'fuel-consumption-converter',
                'description' => 'Convert fuel units (MPG, km/L, L/100km).',
                'category' => 'utility',
                'controller' => 'Tools\Converters\UnitConverterController',
                'route_name' => 'utility.fuel-consumption-converter',
                'url' => '/tools/fuel-consumption-converter',
                'icon_name' => 'fuel-converter',
                'order' => 213,
            ],
            [
                'name' => 'Data Transfer Rate Converter',
                'slug' => 'data-transfer-rate-converter',
                'description' => 'Convert data rate (Mbps, MB/s, Gbps).',
                'category' => 'utility',
                'controller' => 'Tools\Converters\UnitConverterController',
                'route_name' => 'utility.data-transfer-rate-converter',
                'url' => '/tools/data-transfer-rate-converter',
                'icon_name' => 'data-transfer-rate-converter',
                'order' => 214,
            ],

            // Batch D: Specialized
            [
                'name' => 'Cooking Unit Converter',
                'slug' => 'cooking-unit-converter',
                'description' => 'Convert cooking units (tsp, tbsp, cup, ml).',
                'category' => 'utility',
                'controller' => 'Tools\Converters\UnitConverterController',
                'route_name' => 'utility.cooking-unit-converter',
                'url' => '/tools/cooking-unit-converter',
                'icon_name' => 'cooking-unit-converter',
                'order' => 215,
            ],
            [
                'name' => 'Torque Converter',
                'slug' => 'torque-converter',
                'description' => 'Convert torque units (Nm, ft-lb).',
                'category' => 'utility',
                'controller' => 'Tools\Converters\UnitConverterController',
                'route_name' => 'utility.torque-converter',
                'url' => '/tools/torque-converter',
                'icon_name' => 'torque-converter',
                'order' => 216,
            ],
            [
                'name' => 'Density Converter',
                'slug' => 'density-converter',
                'description' => 'Convert density units (kg/m³, g/cm³).',
                'category' => 'utility',
                'controller' => 'Tools\Converters\UnitConverterController',
                'route_name' => 'utility.density-converter',
                'url' => '/tools/density-converter',
                'icon_name' => 'density-converter',
                'order' => 217,
            ],
            [
                'name' => 'Molar Mass Converter',
                'slug' => 'molar-mass-converter',
                'description' => 'Calculate molar mass (g/mol).',
                'category' => 'utility',
                'controller' => 'Tools\Converters\UnitConverterController',
                'route_name' => 'utility.molar-mass-converter',
                'url' => '/tools/molar-mass-converter',
                'icon_name' => 'molar-mass-converter',
                'order' => 218,
            ],
            [
                'name' => 'Frequency Converter',
                'slug' => 'frequency-converter',
                'description' => 'Convert frequency units (Hz, kHz, MHz).',
                'category' => 'utility',
                'controller' => 'Tools\Converters\UnitConverterController',
                'route_name' => 'utility.frequency-converter',
                'url' => '/tools/frequency-converter',
                'icon_name' => 'frequency-converter',
                'order' => 219,
            ],
        ];
    }
}
