<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Tools\Converters\AngleConverterController;
use App\Http\Controllers\Tools\Converters\AreaConverterController;
use App\Http\Controllers\Tools\Converters\AsciiConverterController;
use App\Http\Controllers\Tools\Converters\BinaryHexConverterController;
use App\Http\Controllers\Tools\Converters\BinaryToTextController;
use App\Http\Controllers\Tools\Converters\CamelCaseConverterController;
use App\Http\Controllers\Tools\Converters\CaseConverterController;
use App\Http\Controllers\Tools\Converters\CookingUnitConverterController;
use App\Http\Controllers\Tools\Converters\DataTransferRateConverterController;
use App\Http\Controllers\Tools\Converters\DecimalBinaryConverterController;
use App\Http\Controllers\Tools\Converters\DecimalHexConverterController;
use App\Http\Controllers\Tools\Converters\DecimalOctalConverterController;
use App\Http\Controllers\Tools\Converters\DensityConverterController;
use App\Http\Controllers\Tools\Converters\DigitalStorageConverterController;
use App\Http\Controllers\Tools\Converters\EnergyConverterController;
use App\Http\Controllers\Tools\Converters\ForceConverterController;
use App\Http\Controllers\Tools\Converters\FrequencyConverterController;
use App\Http\Controllers\Tools\Converters\FuelConsumptionConverterController;
use App\Http\Controllers\Tools\Converters\KebabCaseConverterController;
use App\Http\Controllers\Tools\Converters\LengthConverterController;
use App\Http\Controllers\Tools\Converters\MolarMassConverterController;
use App\Http\Controllers\Tools\Converters\NumberBaseConverterController;
use App\Http\Controllers\Tools\Converters\PascalCaseConverterController;
use App\Http\Controllers\Tools\Converters\PowerConverterController;
use App\Http\Controllers\Tools\Converters\PressureConverterController;
use App\Http\Controllers\Tools\Converters\RgbHexConverterController;
use App\Http\Controllers\Tools\Converters\SentenceCaseConverterController;
use App\Http\Controllers\Tools\Converters\SnakeCaseConverterController;
use App\Http\Controllers\Tools\Converters\SpeedConverterController;
use App\Http\Controllers\Tools\Converters\StudlyCaseConverterController;
use App\Http\Controllers\Tools\Converters\TemperatureConverterController;
use App\Http\Controllers\Tools\Converters\TextToBinaryController;
use App\Http\Controllers\Tools\Converters\TorqueConverterController;
use App\Http\Controllers\Tools\Converters\VolumeConverterController;
use App\Http\Controllers\Tools\Converters\WeightConverterController;
use App\Http\Controllers\Tools\Development\Base64EncoderDecoderController;
use App\Http\Controllers\Tools\Development\CodeFormatterController;
use App\Http\Controllers\Tools\Development\CronJobGeneratorController;
use App\Http\Controllers\Tools\Development\CssMinifierController;
use App\Http\Controllers\Tools\Development\CurlCommandBuilderController;
use App\Http\Controllers\Tools\Development\HtmlEncoderDecoderController;
use App\Http\Controllers\Tools\Development\HtmlMinifierController;
use App\Http\Controllers\Tools\Development\HtmlToMarkdownConverterController;
use App\Http\Controllers\Tools\Development\HtmlViewerController;
use App\Http\Controllers\Tools\Development\JsMinifierController;
use App\Http\Controllers\Tools\Development\JsonFormatterController;
use App\Http\Controllers\Tools\Development\JsonParserController;
use App\Http\Controllers\Tools\Development\JsonToCsvConverterController;
use App\Http\Controllers\Tools\Development\JsonToSqlConverterController;
use App\Http\Controllers\Tools\Development\JsonToXmlConverterController;
use App\Http\Controllers\Tools\Development\JsonToYamlConverterController;
use App\Http\Controllers\Tools\Development\JwtDecoderController;
use App\Http\Controllers\Tools\Development\MarkdownToHtmlConverterController;
use App\Http\Controllers\Tools\Development\Md5GeneratorController;
use App\Http\Controllers\Tools\Development\SqlToJsonController;
use App\Http\Controllers\Tools\Development\SqlToJsonConverterController;
use App\Http\Controllers\Tools\Development\UnicodeEncoderDecoderController;
use App\Http\Controllers\Tools\Development\UrlEncoderDecoderController;
use App\Http\Controllers\Tools\Development\UuidGeneratorController;
use App\Http\Controllers\Tools\Development\XmlFormatterController;
use App\Http\Controllers\Tools\Development\XmlToCsvController;
use App\Http\Controllers\Tools\Development\XmlToJsonController;
use App\Http\Controllers\Tools\Development\YamlToJsonController;
use App\Http\Controllers\Tools\Document\ExcelToPdfController;
use App\Http\Controllers\Tools\Document\JpgToPdfController;
use App\Http\Controllers\Tools\Document\PdfCompressorController;
use App\Http\Controllers\Tools\Document\PdfMergerController;
use App\Http\Controllers\Tools\Document\PdfSplitterController;
use App\Http\Controllers\Tools\Document\PdfToExcelController;
use App\Http\Controllers\Tools\Document\PdfToJpgController;
use App\Http\Controllers\Tools\Document\PdfToPptController;
use App\Http\Controllers\Tools\Document\PdfToWordController;
use App\Http\Controllers\Tools\Document\PptToPdfController;
use App\Http\Controllers\Tools\Document\WordToPdfController;
use App\Http\Controllers\Tools\Image\Base64ToImageConverterController;
use App\Http\Controllers\Tools\Image\HeicToJpgConverterController;
use App\Http\Controllers\Tools\Image\IcoConverterController;
use App\Http\Controllers\Tools\Image\ImageCompressorController;
use App\Http\Controllers\Tools\Image\ImageConverterController;
use App\Http\Controllers\Tools\Image\ImageToBase64ConverterController;
use App\Http\Controllers\Tools\Image\JpgToPngConverterController;
use App\Http\Controllers\Tools\Image\JpgToWebpConverterController;
use App\Http\Controllers\Tools\Image\PngToJpgConverterController;
use App\Http\Controllers\Tools\Image\PngToWebpConverterController;
use App\Http\Controllers\Tools\Image\SvgToJpgConverterController;
use App\Http\Controllers\Tools\Image\SvgToPngConverterController;
use App\Http\Controllers\Tools\Image\WebpToJpgConverterController;
use App\Http\Controllers\Tools\Network\DnsLookupController;
use App\Http\Controllers\Tools\Network\DomainToIpController;
use App\Http\Controllers\Tools\Network\InternetSpeedTestController;
use App\Http\Controllers\Tools\Network\IpLookupController;
use App\Http\Controllers\Tools\Network\PingTestController;
use App\Http\Controllers\Tools\Network\PortCheckerController;
use App\Http\Controllers\Tools\Network\ReverseDnsLookupController;
use App\Http\Controllers\Tools\Network\TracerouteController;
use App\Http\Controllers\Tools\Network\UserAgentParserController;
use App\Http\Controllers\Tools\Network\WhatIsMyIpController;
use App\Http\Controllers\Tools\Network\WhatIsMyIspController;
use App\Http\Controllers\Tools\Network\WhoisLookupController;
use App\Http\Controllers\Tools\Seo\BingSerpCheckerController;
use App\Http\Controllers\Tools\Seo\BrokenLinksCheckerController;
use App\Http\Controllers\Tools\Seo\GoogleSerpCheckerController;
use App\Http\Controllers\Tools\Seo\KeywordDensityCheckerController;
use App\Http\Controllers\Tools\Seo\MetaTagAnalyzerController;
use App\Http\Controllers\Tools\Seo\OnPageSeoCheckerController;
use App\Http\Controllers\Tools\Seo\RedirectCheckerController;
use App\Http\Controllers\Tools\Seo\SlugGeneratorController;
use App\Http\Controllers\Tools\Seo\YahooSerpCheckerController;
use App\Http\Controllers\Tools\Spreadsheet\CsvToExcelController;
use App\Http\Controllers\Tools\Spreadsheet\CsvToJsonController;
use App\Http\Controllers\Tools\Spreadsheet\CsvToSqlController;
use App\Http\Controllers\Tools\Spreadsheet\CsvToTsvController;
use App\Http\Controllers\Tools\Spreadsheet\CsvToXmlConverterController;
use App\Http\Controllers\Tools\Spreadsheet\ExcelToCsvController;
use App\Http\Controllers\Tools\Spreadsheet\GoogleSheetsToExcelController;
use App\Http\Controllers\Tools\Spreadsheet\TsvToCsvConverterController;
use App\Http\Controllers\Tools\Spreadsheet\XlsToXlsxController;
use App\Http\Controllers\Tools\Spreadsheet\XlsxToXlsController;
use App\Http\Controllers\Tools\Text\DuplicateLineRemoverController;
use App\Http\Controllers\Tools\Text\FileDifferenceCheckerController;
use App\Http\Controllers\Tools\Text\LoremIpsumGeneratorController;
use App\Http\Controllers\Tools\Text\MorseToTextConverterController;
use App\Http\Controllers\Tools\Text\TextReverserController;
use App\Http\Controllers\Tools\Text\TextToMorseConverterController;
use App\Http\Controllers\Tools\Text\WordCounterController;
use App\Http\Controllers\Tools\Time\DateToUnixTimestampController;
use App\Http\Controllers\Tools\Time\EpochTimeConverterController;
use App\Http\Controllers\Tools\Time\LocalTimeToUtcController;
use App\Http\Controllers\Tools\Time\TimeUnitConverterController;
use App\Http\Controllers\Tools\Time\TimeZoneConverterController;
use App\Http\Controllers\Tools\Time\UnixTimestampToDateController;
use App\Http\Controllers\Tools\Time\UtcToLocalTimeController;
use App\Http\Controllers\Tools\Utility\PasswordGeneratorController;
use App\Http\Controllers\Tools\Utility\QrCodeGeneratorController;
use App\Http\Controllers\Tools\Utility\RandomNumberGeneratorController;
use App\Http\Controllers\Tools\Utility\UsernameCheckerController;
use App\Http\Controllers\Tools\Youtube\YoutubeChannelDataExtractorController;
use App\Http\Controllers\Tools\Youtube\YoutubeChannelIdFinderController;
use App\Http\Controllers\Tools\Youtube\YoutubeEarningsCalculatorController;
use App\Http\Controllers\Tools\Youtube\YoutubeHandleCheckerController;
use App\Http\Controllers\Tools\Youtube\YoutubeMonetizationCheckerController;
use App\Http\Controllers\Tools\Youtube\YoutubeTagGeneratorController;
use App\Http\Controllers\Tools\Youtube\YoutubeThumbnailDownloaderController;
use App\Http\Controllers\Tools\Youtube\YoutubeVideoDataExtractorController;
use App\Http\Controllers\Tools\Youtube\YoutubeVideoTagsExtractorController;


$locales = ['', 'ru', 'es', 'fr', 'de', 'it', 'pt', 'tr', 'ar', 'zh', 'ja', 'id', 'ko', 'fi', 'vi', 'nl', 'pl', 'no', 'cs', 'sv', 'ro', 'da', 'hi'];

foreach ($locales as $prefix) {
    Route::prefix($prefix)->group(function () use ($prefix) {
        $n = function ($name) use ($prefix) {
            return ($prefix === '') ? $name : null;
        };

        require __DIR__ . '/web_content.php';
    });
}

require __DIR__ . '/auth.php';
require __DIR__ . '/admin.php';
